acme_films:
    resource: "@AcmeFilmsBundle/Resources/config/routing.yml"
    prefix:   /

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"
    prefix: /{_locale}

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /{_locale}/profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /{_locale}/register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /{_locale}/resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /{_locale}/profile

#hwi_oauth_redirect:
#    resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
#    prefix:   /connect
##facebook_login:
##    pattern: /login/check-facebook
#google_login:
#    pattern: /login/check-google
##custom_login:
##    pattern: /login/check-custom
##github_login:
##    pattern: /login/check-github



_security_check:
    pattern:  /{_locale}/login_check
_security_logout:
    pattern:  /{_locale}/logout
fos_facebook_channel:
    resource: "@FOSFacebookBundle/Resources/config/routing.xml"
#_facebook_secured:
#    pattern: /secured/
#    defaults: { _controller: AcmeDemoBundle:Welcome:index }