security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        chain_provider:
              chain:
                  providers: [fos_userbundle, my_fos_facebook_provider]
        fos_userbundle:
            id: fos_user.user_provider.username
        my_fos_facebook_provider:
            id: my.facebook.user   # see "Example Custom User Provider using the FOS\UserBundle" chapter further down
#            memory:
#                users:
#                    ryan:  { password: ryanpass, roles: 'ROLE_USER' }
#                    admin: { password: kitten, roles: 'ROLE_ADMIN' }

    firewalls:
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_provider: form.csrf_provider
            fos_facebook:
                app_url: "http://apps.facebook.com/appName/"
                server_url: "http://films.local/"
                login_path: /login
                check_path: /facebook-check
                default_target_path: /
                provider: my_fos_facebook_provider
            logout:       true
            anonymous:    true

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: ROLE_ADMIN }
        - { path: /new, role: ROLE_SUPER_ADMIN }
        - { path: /edit, role: ROLE_SUPER_ADMIN }
        - { path: /delete, role: ROLE_SUPER_ADMIN }

        - { path: ^/secured/.*, role: [IS_AUTHENTICATED_FULLY] } # This is the route secured with fos_facebook
        - { path: ^/facebook/,  role: [ROLE_FACEBOOK] }
        - { path: ^/.*,         role: [IS_AUTHENTICATED_ANONYMOUSLY] }

    acl:
            connection: default